const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./app.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "RCSM API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "15.207.19.252:3000",
  basePath: "/",
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./app.js");
});
